DATAWVE-1017: updating tokenParser to handle newer filter format
NationalSecurityAgency/datawave pull request #1018
Opened 2020-12-16 16:27 UTC by mineralntl

2021-01-04 18:26 UTC, matthpeterson submitted a review, later dismissed

2021-02-11 19:53 UTC, ivakegg requested changes

2021-02-11 19:53 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/iterators/filter/TokenSpecParser.java
> +            WORD("(?:[a-z]{6,})"),
why does a word have to be at least 6 characters?

2021-02-11 19:53 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/iterators/filter/TokenSpecParser.java
> +            STRLITERAL2("[\\w]{6,}"),
Why does a string literal need to be at least 6 characters?

2021-03-17 12:59 UTC, ivakegg commented
Superseded by #1113

2021-03-17 12:59 UTC, closed without merging