Datawave 1023
NationalSecurityAgency/datawave pull request #1024
Opened 2020-12-23 16:22 UTC by plainolneesh

While testing for the periodic test failures (see #637) and (#1023), I found two tests that would fail because repetitive runs would hit the list limits.

2020-12-23 16:54 UTC, ivakegg approved these changes

2020-12-23 16:55 UTC, apmoriarty approved these changes

2020-12-23 16:56 UTC, ivakegg commented
Looks like some of the files need to be run through the formatter first.  Do a full build (mvn clean install -Ddist -Pexamples) and then commit the formatting changes.

2021-01-04 20:56 UTC, ivakegg requested changes

2021-01-04 20:56 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionRegexQueryTest.java
>          assertTrue(countComplete(dirs) >= 1);
Don't need the assertTrue if the assertEquals is good....

2021-01-04 20:56 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionRegexQueryTest.java
>          assertTrue(countComplete(dirs) >= 1);
Same comment as above.

2021-01-08 14:04 UTC, ivakegg commented
It appears there are formatting issues.  Please run the formatter and check in any changes (mvn -V -B -e clean formatter:format sortpom:sort -Pautoformat)

2021-01-08 14:45 UTC, ivakegg requested changes

2021-01-08 14:45 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionRegexQueryTest.java
> +        dirs.clear();
How exactly is this supposed to help?  At line 273 we reassign the dirs variable so I am a little confused as to how this fixes the periodic failure.

2021-02-22 17:10 UTC, ivakegg approved these changes

2021-02-22 17:11 UTC, merged