Web docker
NationalSecurityAgency/datawave pull request #1050
Opened 2021-01-28 13:48 UTC by alerman

2021-01-28 23:50 UTC, keith-ratcliffe requested changes
Seems good, just wondering about the empty README...maybe inadvertent
 web-services/deploy/application/src/main/docker/README.md

2021-01-29 11:16 UTC, alerman commented
Readme was mistakenly added. Deleted the file.

2021-02-03 16:08 UTC, keith-ratcliffe approved these changes

2021-02-04 10:14 UTC, apmoriarty approved these changes
LGTM

2021-02-04 10:55 UTC, merged