Delayed index only field-values are now added to the candidate document.
NationalSecurityAgency/datawave pull request #1145
Opened 2021-04-13 18:03 UTC by apmoriarty

Index only fields fetched in a delayed fashion are not added to the document returned from the QueryIterator. The query is still functionally correct but HIT_TERMS will fail to report a hit term.

2021-04-20 15:55 UTC, FineAndDandy requested changes

2021-04-26 12:30 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/DelayedNonEventIndexContext.java
> +            if (obj instanceof FunctionalSet<?>) {
Debugged the added test again to confirm and the single field-value pair is stored in the underlying map as a FunctionalSet.

2021-05-13 09:47 UTC, alerman approved these changes

2021-05-13 10:35 UTC, FineAndDandy approved these changes

2021-05-13 10:35 UTC, merged