Removing User who is no longer contributing and add another.
NationalSecurityAgency/datawave pull request #1216
Opened 2021-07-06 15:00 UTC by alerman

2021-07-07 10:43 UTC, apmoriarty approved these changes

2021-07-12 15:51 UTC, ivakegg approved these changes

2021-07-15 13:26 UTC, jwomeara requested changes

2021-07-15 13:26 UTC, jwomeara commented on CODEOWNERS
> +*	@brianloss @ivakegg @drewfarris @keith-ratcliffe @cawaring @tomnelson @jwomeara @billoley @matthpeterson @ejrgilbert @alerman @hlgp @jschmidt10 @apmoriarty
Might I suggest that we stop maintaining this list and finally delete it like we talked about? 

```suggestion
```

2021-09-15 15:17 UTC, alerman commented
Closing PR as we are moving away from CODEOWNERS

2021-09-15 15:17 UTC, closed without merging