Re: Issue 454 - added FullTableScanDisallowedException
NationalSecurityAgency/datawave pull request #1261
Opened 2021-08-24 03:18 UTC by plainolneesh

Updated the randomly failing testMaxValueNegAnyField

2021-08-26 16:25 UTC, ivakegg requested changes

2021-08-26 16:25 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionIndexOnlyQueryTest.java
> +        } catch (FullTableScansDisallowedException e) {
I am quite confused here.  If we were catching RuntimeException before and this was only failing periodically then how does replacing what we are catching going to make this any better?  Wouldn't we still need to catch a RuntimeException?  Also if we are only periodically throwing a FullTableScansDisallowedException, then why is that not the exception always being thrown?

2021-08-27 21:32 UTC, codebyneesh commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionIndexOnlyQueryTest.java
> +        } catch (FullTableScansDisallowedException e) {
From what I saw, this test has been ignored since ~2019.  When I ran it, it was only throwing the full table scan required error. I figured between then and now, something has been updated that could've possibly impacted the periodic failure.

2021-09-01 16:55 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/MaxExpansionIndexOnlyQueryTest.java
> +        } catch (FullTableScansDisallowedException e) {
Ah, I see.  Thanks.

2021-09-01 16:55 UTC, ivakegg approved these changes

2021-09-17 13:36 UTC, jschmidt10 approved these changes

2021-09-30 13:56 UTC, merged