fixes #1263 Add filter:compare function that can work over group of values
NationalSecurityAgency/datawave pull request #1264
Opened 2021-08-24 20:01 UTC by d-hwang

2021-08-25 16:56 UTC, apmoriarty approved these changes, later dismissed

2021-08-25 17:33 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/CompareFunction.java
> +        if (this.parameterList.size() != 4 && !"ANY".equalsIgnoreCase(this.parameterList.get(2)) && "ALL".equalsIgnoreCase(this.parameterList.get(2))) {
!"ALL".equalsIgnoreCase(this.parameterList.get(2))

2021-08-25 17:34 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/CompareFunction.java
> +        if (this.parameterList.size() != 4 && !"ANY".equalsIgnoreCase(this.parameterList.get(2)) && "ALL".equalsIgnoreCase(this.parameterList.get(2))) {
please add a unit test for this as well

2021-08-25 17:36 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +        } catch (NullPointerException npe) {
no!

2021-08-25 17:39 UTC, FineAndDandy requested changes
almost there

2021-08-25 19:00 UTC, d-hwang commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +        } catch (NullPointerException npe) {
throwing custom exception now.

2021-08-25 19:00 UTC, d-hwang commented on warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/CompareFunction.java
> +        if (this.parameterList.size() != 4 && !"ANY".equalsIgnoreCase(this.parameterList.get(2)) && "ALL".equalsIgnoreCase(this.parameterList.get(2))) {
updated to use enum.

2021-08-26 16:34 UTC, ivakegg requested changes

2021-08-26 16:34 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +    public static boolean compare(Object field, String operator, String compareMode, Object field2) {
You are missing changes to the EvaluationPhaseFilterFunctionsDescriptor class.  In particular the fieldsForNormalization, fields, fieldSets, and possibly the addFilters functions.

2021-08-26 18:24 UTC, d-hwang commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +    public static boolean compare(Object field, String operator, String compareMode, Object field2) {
I updated fields/fieldSets. I don't think I need to modify addFilters, since I don't want any filters before evaluating field1==field2? I also don't need to apply FunctionNormalizationRebulidingVisitor since there aren't any terms to normalize in the argument. Let me know if this sounds appropriate, but I may be missing something. Thanks for any insights.

2021-08-27 12:01 UTC, apmoriarty submitted a review, later dismissed
LGTM

2021-08-27 12:01 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +        throw new IllegalArgumentException("cannot use " + operator + " in this equation");
Perhaps also include 'matchesAny' in the exception?

2021-08-27 13:23 UTC, d-hwang commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +        throw new IllegalArgumentException("cannot use " + operator + " in this equation");
Updated.

2021-08-30 13:38 UTC, apmoriarty approved these changes, later dismissed

2021-09-03 13:43 UTC, FineAndDandy approved these changes, later dismissed

2021-09-03 13:53 UTC, ivakegg approved these changes, later dismissed

2021-10-01 14:18 UTC, ivakegg approved these changes

2021-10-01 14:36 UTC, apmoriarty approved these changes

2021-10-01 15:21 UTC, merged