Feature/parallel index lookup
NationalSecurityAgency/datawave pull request #1307
Opened 2021-10-08 17:22 UTC by jwomeara

This updates our index lookup code to expand bounded ranges in parallel, stops the regex expansion visitor from creating twice as many threads as it needs, and generally attempts to clean up the index lookup and term expansion logic.

2021-10-08 17:29 UTC, jwomeara commented
One thing I didn't do in this PR that I could have was to make the field index lookup parallel as well.  That would be a trivial thing to add.  Would any reviewers like me to do that?  Are there any good reasons NOT to do that?

2021-10-08 18:29 UTC, keith-ratcliffe commented
> One thing I didn't do in this PR that I could have was to make the field index lookup parallel as well. That would be a trivial thing to add. Would any reviewers like me to do that? Are there any good reasons NOT to do that?

Hmm, no reason that I can think of. @ivakegg?

2021-10-08 18:50 UTC, jwomeara commented
Updated the field index lookups to be asynchronous as well.  If anyone has a legitimate objection I can always revert that commit.

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +                }
What happens if we have a partial expansion?

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +            // timeout exception and except ( a max lookup specified ) 3) we receive a value under timeout and we break
I recognize this code is carried over, but why would we ever want to handle the first case? I can't think of a good reason to let a scanner sit on the global index for an extended period of time.

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/RegexIndexLookup.java
> +                }
```suggestion
                if (log.isTraceEnabled()) {
                    log.trace("Do we have next? " + iter.hasNext());
                }
```

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +     * Serves as a means to associate index lookup threads with a particular Index Expansion Visitor
```suggestion
     * Associates index lookup threads with a particular Index Expansion Visitor
```

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
> +        }
```suggestion
        if (this.indexOnlyFields.contains(erField)) {
            return true;
        } else {
            // else determine the need to expand terms based on whether other terms will dominate
            return ascendTree(node, Maps.newIdentityHashMap());
        }
```

2021-10-12 10:03 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
> +            // necessary
Is this comment necessary? If so, why doesn't the datatype filter matter?

2021-10-12 13:38 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +            // timeout exception and except ( a max lookup specified ) 3) we receive a value under timeout and we break
field name lookups should be given as long as needed to expand.

2021-10-12 13:39 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +                }
The same thing that has always happened...  If we timeout, we drop whatever has been expanded so far and replace it with exceeded value threshold.

2021-10-12 13:47 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
> +            // necessary
Good question.  In my opinion, questions like this are outside the scope of this PR since the overall goal was just to parallelize the existing logic.  If you didn't already know, this comment was carried forward from the original code.  So, for now I'd be happy to leave this as an exercise for the reader.

2021-10-12 14:19 UTC, ivakegg requested changes

2021-10-12 14:19 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +            // Deal with the case we we let ourselves get interrupted AND support timeout.
lets not talk about wewe here

2021-10-12 14:19 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +        executor = new ThreadPoolExecutor(threads, threads, 0, TimeUnit.MILLISECONDS, new SynchronousQueue<>(true), new IndexExpansionThreadFactory(
need an unbounded linked queue here

2021-10-12 14:33 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +        executor = new ThreadPoolExecutor(threads, threads, 0, TimeUnit.MILLISECONDS, new SynchronousQueue<>(true), new IndexExpansionThreadFactory(
Yes, I remember when I said that to you.  lol

2021-10-12 14:35 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/AsyncIndexLookup.java
> +            // Deal with the case we we let ourselves get interrupted AND support timeout.
removed.  didn't mean to make you uncomfortable.

2021-10-12 14:37 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
> +            // necessary
Alternatively, if you're concerned about the implications of this comment, please create a ticket.

2021-10-12 14:37 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/BaseRegexIndexLookup.java
> +public abstract class BaseRegexIndexLookup extends AsyncIndexLookup {
Do we need this class?  merge into the RegexIndexLookup perhaps.

2021-10-12 16:25 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeIndexExpansionVisitor.java
> +    protected void rebuildFutureJexlNode(FutureJexlNode futureJexlNode) {
@Override

2021-10-12 16:37 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeIndexExpansionVisitor.java
> +    protected void rebuildFutureJexlNode(FutureJexlNode futureJexlNode) {
done

2021-10-12 17:03 UTC, ivakegg submitted a review, later dismissed

2021-10-13 08:54 UTC, apmoriarty submitted a review, later dismissed

2021-10-13 08:54 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
> +            // necessary
Agreed that this is outside the scope, I figured on the off chance you knew we could clarify what's going on here.

2021-10-14 18:14 UTC, keith-ratcliffe submitted a review, later dismissed
Looks like your 2 prior approvals got nixed. 
The changes look really good to me, and the nits I pointed out can remain, as far as I'm concerned....
(Should also have mentioned, I ran query tests on this patch overnight on our test cluster. No issues)

2021-10-14 18:14 UTC, keith-ratcliffe commented on warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
>  import datawave.query.jexl.nodes.BoundedRange;
Unused import, BoundedRange

2021-10-14 18:14 UTC, keith-ratcliffe commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +    private static final Logger log = Logger.getLogger(BaseIndexExpansionVisitor.class);
Aspirational logger? Never seems to be used ;)

2021-10-14 18:14 UTC, keith-ratcliffe commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
> +        return (IndexLookup) new RegexIndexLookup(config, scannerFactory, fields, reverseFields, patterns, helperRef, true, execService);
Shouldn't need the IndexLookup cast here anymore

2021-10-14 18:14 UTC, keith-ratcliffe commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/ShardIndexQueryTableStaticMethods.java
> +        return (IndexLookup) new RegexIndexLookup(config, scannerFactory, fieldName, patterns, helperRef, execService);
Shouldn't need the IndexLookup cast here anymore

2021-10-14 18:14 UTC, keith-ratcliffe commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/UnfieldedIndexExpansionVisitor.java
> +    private static final Logger log = Logger.getLogger(UnfieldedIndexExpansionVisitor.class);
Unused logger

2021-10-14 19:28 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
>  import datawave.query.jexl.nodes.BoundedRange;
not unused.  i suspect it may be unused in your special branch: issue-1068-asyncIndexLookup

2021-10-14 20:53 UTC, keith-ratcliffe submitted a review, later dismissed

2021-10-19 11:02 UTC, apmoriarty submitted a review, later dismissed

2021-10-20 14:14 UTC, ivakegg submitted a review, later dismissed

2021-10-25 14:23 UTC, jwomeara commented
Merge conflict resolution requires reapproval when you all get a chance.

2021-10-25 14:28 UTC, ivakegg approved these changes

2021-10-25 14:30 UTC, apmoriarty approved these changes

2021-10-26 20:41 UTC, merged