1301: Porting unit tests to repo
NationalSecurityAgency/datawave pull request #1309
Opened 2021-10-12 12:59 UTC by avgAGB

2021-10-13 12:36 UTC, jwomeara submitted a review, later dismissed
LGTM

2021-10-13 12:38 UTC, apmoriarty approved these changes

2021-10-19 10:59 UTC, apmoriarty requested changes

2021-10-19 10:59 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +    }
For tests like these I would like to see something like this, basically extract common code to a test method. It seems like overkill for the case of a single equality node, but as the query gets more complex the tests become easier to read.
```
public void testSimpleExpression(){
  String query = "FOO == 'bar'";
  test(query, query);
}
...
private void test(String query, String expected){
  test(query, expected, config);  // pass in the default shard query config
}

private void test(String query, String expected, ShardQueryConfiguration config){
  ASTJexlScript script = JexlASTHelper.parseJexlQuery(query);
  ASTJexlScrit pushed = PushdownLargeFieldedLists(confg, script, null, null)
}
```

2021-10-19 10:59 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +        Assert.assertEquals("EXPECTED: " + expected + "\nACTUAL: " + rewritten, expected, rewritten);
my personal preference is static imports for asserts, this isn't a blocker

2021-10-19 10:59 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +                        rewritten);
You can still extract common code in the case of a pushed visitor. You could do something like this
```
public void test(){
  String query = 'your query here"
  String expectedLeft = "((_List_ = true) && ((id = '";
  String expectedRight = "the rest of your quey here";
  test(query, expectedLeft, expectedRight, config);
}
...
// and then essentially a copy of the original test method, but with updated asserts to
// handle the pushed value query
```

2021-10-19 10:59 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +    public void testPushdownFst() throws Throwable {
Are there plans to add more comprehensive FST test? If so, might be worth extracting some of these variables/functions

2021-10-19 11:56 UTC, avgAGB commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +    }
I understand the reformatting suggestions, though my question is would that cause an issue if the unit test code here looks different than it does elsewhere? The acceptance criteria on the ticket seemed to suggest the unit test code be moved here as it existed before.

EDIT: Per our sidechat, I'll made adjustments in future commits and look to remove redundant copies once this is merged.

2021-10-19 12:38 UTC, avgAGB commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +        Assert.assertEquals("EXPECTED: " + expected + "\nACTUAL: " + rewritten, expected, rewritten);
Will adjust this in the next commit

2021-10-19 16:18 UTC, avgAGB commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +                        rewritten);
Updated in latest commit.

2021-10-19 16:19 UTC, avgAGB commented on warehouse/query-core/src/test/java/datawave/query/rewrite/jexl/visitors/PushdownLargeFieldedListsVisitorTest.java
> +    public void testPushdownFst() throws Throwable {
I don't have plans to add a more comprehensive test for this particular ticket, however I tried to pull out some of the setup and the pushdown to keep it in line with the other unit tests.

2021-10-20 14:17 UTC, ivakegg approved these changes

2021-10-20 15:03 UTC, apmoriarty approved these changes

2021-10-26 14:15 UTC, merged