Update for MinimalReferenceExpressionsVisitor
NationalSecurityAgency/datawave pull request #1318
Opened 2021-10-19 09:55 UTC by apmoriarty

Update for MinimalReferenceExpressionsVisitor to handle special case for assignment nodes.

2021-10-20 14:28 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitor.java
> +        JexlASTHelper.validateLineage(node, true);
Is this not overkill?

2021-10-20 14:28 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitor.java
> +            boolean isMarkerNode = QueryPropertyMarkerVisitor.getCopiedInstance(node).isAnyType();
why copy?

2021-10-20 14:29 UTC, ivakegg requested changes
I don't quite understand purpose of copying.

2021-10-28 17:07 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitor.java
> +        JexlASTHelper.validateLineage(node, true);
I'll remove that, it's a vestige from testing

2021-10-28 17:11 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/validate/MinimalReferenceExpressionsVisitor.java
> +            boolean isMarkerNode = QueryPropertyMarkerVisitor.getCopiedInstance(node).isAnyType();
That was a workaround until https://github.com/NationalSecurityAgency/datawave/pull/1297 could get merged. My preference is to get that in first, and then update this merge request

2021-12-22 14:59 UTC, ivakegg approved these changes

2021-12-29 15:29 UTC, jschmidt10 approved these changes

2021-12-29 15:32 UTC, merged