Improve test coverage of EvaluationPhaseFilterFunctions
NationalSecurityAgency/datawave pull request #1320
Opened 2021-10-19 11:44 UTC by lbschanno

Add a wide range of unit tests to improve test coverage for `EvaluationPhaseFilterFunctions`. In addition, improve documentation, and fix a few small bugs.

I began this work with the intent of familiarizing myself with `EvaluationPhaseFilterFunctions` in order to address issues with the occurrence function as described in #1108. However, the intended behavior of the occurrence function is still not clear, and potentially buggier than thought. See the test suite OccurrenceIterableValueTests.testsToShowOddBehavior() to see examples. It appears that the total count will reset whenever a new ValueTuple with a Type as its second property is seen in an Iterable argument.

2021-10-19 14:36 UTC, apmoriarty submitted a review, later dismissed
LGTM, someone with more knowledge of this area of the code should take a look

2021-10-19 18:58 UTC, ivakegg requested changes

2021-10-19 18:58 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
> +            assertTrue(resultForOperator(1)); // The total number of LcNoDiacriticsType instances seen (1).
I don't think the type should matter.  This should probably be 3.

2021-10-19 18:58 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
> +            assertTrue(resultForOperator(5)); // The count of the last type, NoOpType, seen (2) plus the number of non-typed objects seen after that (3).
This one does not make any sense to me.  This should be 3 as well I would expected (typed values only).

2021-10-19 18:58 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
> +            assertTrue(resultForOperator(8)); // Returns the total number of objects seen (8).
I am thinking this should be 4 as well.

2021-10-19 18:58 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctionsTest.java
> +        public void testsToShowOddBehavior() {
So I think I may have gotten clarification on what this function should do from a user standpoint.  The function needs to count all of the instances of a field in an event/document.  What this means is that fields that are in the events AND are found in the index because the query was searching on it should only count the fields that came from the event (the indexed values are added separately to the context).  However if the field is index-only, then and only then should it count the fields added to the context from the index.

2021-10-26 16:14 UTC, ivakegg approved these changes

2021-10-28 20:59 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +    private EvaluationPhaseFilterFunctions() {
Please remove this private constructor.  There is a test case on the other side that extends this class and this breaks it.

2021-10-28 21:05 UTC, ivakegg requested changes
see comments

2021-11-02 15:06 UTC, lbschanno commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/EvaluationPhaseFilterFunctions.java
> +    private EvaluationPhaseFilterFunctions() {
Fixed.

2021-11-08 10:55 UTC, apmoriarty approved these changes

2021-11-08 13:29 UTC, ivakegg approved these changes

2021-11-09 12:49 UTC, merged