fixes #1338: Always check skipped terms after attempting to traverse …
NationalSecurityAgency/datawave pull request #1339
Opened 2021-11-04 15:22 UTC by FineAndDandy

…if not done

2021-11-04 15:33 UTC, apmoriarty requested changes

2021-11-04 15:33 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
> +        Assert.assertTrue(expect(o, true));
Let's add a comment saying that "offset 252, 252, 253 evaluates to true"

2021-11-04 15:33 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
> +        Assert.assertTrue(expect(o, true));
Comment indicating why this is a reverse and not a forward match?

2021-11-04 15:33 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
> +        Assert.assertTrue(expect(o, true));
Comment "All terms share index 252"

2021-11-04 15:33 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/ContentFunctionsTest.java
> +        Assert.assertTrue(expect(o, true));
Comment "All terms share index 252".

Do these last two cases actually exercise the forward/reverse matching logic? The offsets appear to be identical.

2021-11-08 10:57 UTC, apmoriarty approved these changes

2021-11-08 13:10 UTC, ivakegg approved these changes

2021-11-08 13:41 UTC, merged