Clarify TTL calculation with comment
NationalSecurityAgency/datawave pull request #1349
Opened 2021-11-16 15:44 UTC by matthpeterson

2021-11-18 15:10 UTC, jschmidt10 submitted a review, later dismissed

2021-11-19 15:05 UTC, apmoriarty approved these changes, later dismissed
LGTM

2021-11-19 15:10 UTC, ivakegg requested changes

2021-11-19 15:10 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/iterators/filter/TokenizingFilterBase.java
> +            // cutoffTimestamp is currently offset by the default TTL. Start by undoing that default offset
Excellent.  good job

2021-11-19 15:10 UTC, ivakegg commented on warehouse/core/src/test/java/datawave/iterators/filter/ColumnVisibilityLabeledFilter.java
> +                    // deduct TTL for this key
Just a thought, but should we switch these two statements to be consistent with the other class?

2021-11-19 15:15 UTC, matthpeterson commented on warehouse/core/src/test/java/datawave/iterators/filter/ColumnVisibilityLabeledFilter.java
> +                    // deduct TTL for this key
ok will do

2021-11-19 16:02 UTC, ivakegg approved these changes

2021-11-19 16:17 UTC, apmoriarty approved these changes

2021-11-19 16:17 UTC, merged