Fix #1063: Skip TimingMetadata entries when applying Unique transform…
NationalSecurityAgency/datawave pull request #1369
Opened 2021-12-06 19:56 UTC by friedlou

…. (#1162)

* Fix #1063: Skip TimingMetadata entries when applying Unique transform.

* Removed left over commented out tests for debugging.

* Used isFinalDocumentKey to test if document is TIMING_METADATA, as suggested in PR comment.

* Removed unused method.

* Formatting

Co-authored-by: Eluzor Friedman efriedm <efriedm@ip-10-113-15-250.evoforge.org>
Co-authored-by: Moriarty <22225248+apmoriarty@users.noreply.github.com>
Co-authored-by: Ivan Bella <ivan@bella.name>

2021-12-29 13:00 UTC, apmoriarty requested changes
Downgrade log levels to trace and I think this is good to go

2021-12-29 13:00 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
> +            log.info("UniqueTransform.apply " + keyDocumentEntry.getKey() + " " + keyDocumentEntry.getValue().get("UUID.0"));
Even after filtering down the documents logged to those that match the query, this will still generate a tremendous amount of logging. Can you wrap this in a `isTraceEnabled` statement, similar to this?

```java
if(log.isTraceEnabled()) {
   log.trace(....
}
```

2021-12-29 13:00 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
> +                    log.info("Dup blank field. Fields: " + document.getDictionary().keySet() + " " + document.get("UUID.0"));
Same comment, re:downgrading log level to trace

2022-02-01 16:49 UTC, friedlou commented on warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
> +            log.info("UniqueTransform.apply " + keyDocumentEntry.getKey() + " " + keyDocumentEntry.getValue().get("UUID.0"));
Just used for a debugging attempt. Removed in latest commit,

2022-02-01 16:50 UTC, friedlou commented on warehouse/query-core/src/main/java/datawave/query/transformer/UniqueTransform.java
> +                    log.info("Dup blank field. Fields: " + document.getDictionary().keySet() + " " + document.get("UUID.0"));
Removed , as above.

2022-02-03 15:51 UTC, alerman approved these changes

2022-02-16 13:26 UTC, ivakegg approved these changes

2022-02-23 17:35 UTC, apmoriarty approved these changes

2022-02-23 20:28 UTC, merged