fixes #1364 Process all eligible IndexStreams in Union.advanceQueue()
NationalSecurityAgency/datawave pull request #1374
Opened 2021-12-20 14:11 UTC by FineAndDandy

2021-12-20 14:15 UTC, apmoriarty approved these changes, later dismissed

2021-12-20 14:15 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
> +                // children.add(itr);
remove this comment

2021-12-20 18:12 UTC, alerman approved these changes

2021-12-21 16:01 UTC, ivakegg requested changes

2021-12-21 16:01 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
> +                processedChildren.add(itr);
Do we always need to add it back in or only if it is a day?

2021-12-21 16:01 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
> +            if (children.isEmpty() && !processedChildren.isEmpty()) {
Do the children need to be empty to add them in here?  And then if that is the case perhaps the code from 198-205 is not needed?

2021-12-21 16:47 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
> +                processedChildren.add(itr);
ah I see.... just adding it into a new list.

2021-12-21 16:54 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/index/lookup/Union.java
> +            if (children.isEmpty() && !processedChildren.isEmpty()) {
Ah I see.... need to allow children to get empty first.

2021-12-21 16:54 UTC, ivakegg approved these changes

2021-12-22 18:25 UTC, merged