Add visibility/authorization validation to unit test framework
NationalSecurityAgency/datawave pull request #1388
Opened 2022-01-06 18:42 UTC by drewfarris

Currently the unit test framework doesn't do anything to validate the operations of authorizations and visibilities. This PR changes the `CitiesDataType` to use its [ACCESS](https://github.com/NationalSecurityAgency/datawave/blob/afbdc0546c23562dfa5e66a193a094f574200609/warehouse/query-core/src/test/java/datawave/query/testframework/CitiesDataType.java#L87) field to populate the `columnVisibility` security marking in events and then adds a test to validate that they are operating  correctly.

Minor modifications are made elsewhere, such as other tests in datawave-query-core, in order to work with this new approach.

As a part of this work, it was necessary to produce an `ExtendedTestCSVIngestHelper` in order to properly propagate security markings to the `NormalizedContentInterface` instances generated by the `ExtendedCSVIngestHelper` produced when reading events from a sequence file in the [CSVTestFileLoader](https://github.com/NationalSecurityAgency/datawave/blob/afbdc0546c23562dfa5e66a193a094f574200609/warehouse/query-core/src/test/java/datawave/query/testframework/CSVTestFileLoader.java#L33)

2022-01-06 21:55 UTC, keith-ratcliffe requested changes
Aside from the the one comment, looks good. Thanks for adding this!

2022-01-06 21:55 UTC, keith-ratcliffe commented on warehouse/query-core/src/test/java/datawave/query/QueryAuthsTest.java
> +        // }
No longer needed?

2022-01-07 10:34 UTC, apmoriarty submitted a review, later dismissed
Agree with Keith's comment, otherwise LGTM!

2022-01-07 13:17 UTC, keith-ratcliffe approved these changes

2022-01-07 13:35 UTC, apmoriarty approved these changes

2022-01-07 13:49 UTC, merged