Move includeText to QueryFunctions
NationalSecurityAgency/datawave pull request #1534
Opened 2022-04-25 23:30 UTC by lbschanno

The filter:includeText function is not truly evaluation-only, and as
such, does not truly belong in EvaluationPhaseFilterFunctions. Move it
to QueryFunctions.

Done per a request from @ivakegg

2022-05-03 18:34 UTC, ivakegg requested changes
In addition to my comments, you are missing a change in the datawave.query.language.functions.jexl.Text class.  toString needs to output f:includeText instead of filter:includeText

2022-05-03 18:34 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
> +                return JexlNodeFactory.buildNode((ASTERNode) null, field, value);
This should be an EQ node

2022-05-03 18:34 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
> +                    JexlNode kid = JexlNodeFactory.buildNode((ASTERNode) null, field, value);
This should be an EQ node

2022-05-03 19:05 UTC, lbschanno commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
> +                return JexlNodeFactory.buildNode((ASTERNode) null, field, value);
Fixed.

2022-05-03 19:05 UTC, lbschanno commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/QueryFunctionsDescriptor.java
> +                    JexlNode kid = JexlNodeFactory.buildNode((ASTERNode) null, field, value);
Fixed.

2022-06-06 12:16 UTC, ivakegg submitted a review, later dismissed

2022-06-06 16:25 UTC, apmoriarty approved these changes

2022-06-29 09:48 UTC, apmoriarty approved these changes, later dismissed

2022-06-29 12:32 UTC, apmoriarty approved these changes, later dismissed

2022-09-27 16:16 UTC, ivakegg approved these changes, later dismissed

2022-10-04 12:59 UTC, ivakegg commented
I merely resolved conflicts with a rebase and the force pushed.  There were already two approvals for this PR.

2022-10-04 13:23 UTC, apmoriarty approved these changes

2022-10-04 14:44 UTC, merged