Formatting for query and plan on query metrics page (#1593)
NationalSecurityAgency/datawave pull request #1611
Opened 2022-06-08 13:44 UTC by kevinrr888

2022-06-08 13:46 UTC, kevinrr888 commented
Currently have the formatMetrics(List<QueryMetric> metrics) method in JexlFormattedStringBuildingVisitor. Can be moved to a more appropriate class if desired.

2022-06-08 19:21 UTC, ivakegg requested changes

2022-06-08 19:21 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                QueryException qe = new QueryException(DatawaveErrorCode.QUERY_EXECUTION_ERROR, e);
If we cannot parse the query, then lets leave the original query in the metric.  This should not cause an exception.

2022-06-08 19:21 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                    QueryException qe = new QueryException(DatawaveErrorCode.QUERY_EXECUTION_ERROR, e);
If we fail to parse the query, then simply leave the original query in the metric.  We should not be throwing an exception here.

2022-06-08 19:21 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                    for (String line : PrintingVisitor.formattedQueryStringList(queryNode)) {
Lets change this to:
```
if (log.isTraceEnabled()) {
  log.trace(PrintingVisitor.formattedQueryString(queryNode));
}
```

2022-06-08 19:21 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                for (String line : PrintingVisitor.formattedQueryStringList(planNode)) {
Lets change this for loop to:
```
if (log.isTraceEnabled()) {
  log.trace(PrintingVisitor.formattedQueryString(queryNode));
}
```

2022-06-09 14:38 UTC, ivakegg requested changes

2022-06-09 14:38 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                    log.error("");
remove this line

2022-06-09 14:38 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/JexlFormattedStringBuildingVisitor.java
> +                log.error("");
remove this line

2022-06-09 15:32 UTC, ivakegg approved these changes

2022-06-09 15:34 UTC, merged