Task/reduce term frequency search space
NationalSecurityAgency/datawave pull request #1632
Opened 2022-06-24 15:23 UTC by apmoriarty

2022-07-26 14:08 UTC, FineAndDandy requested changes

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/core/iterators/TermFrequencyIterator.java
> +                source.next();
should this allow the scanner to continue or throw an error?

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/core/iterators/key/TFKey.java
> +        return backing != null && nulls.size() >= 3;
good chance to rename nulls to something that makes sense

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/TermFrequencyList.java
>      public static String getEventId(Key key) {
this could probably be rolled into DatawaveKey

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +    private boolean isTld = false;
duplicate property from tfConfig?

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +            } else {
what about ancestor?

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +                        hits.add(new Text(datatype + '\u0000' + uid + '\u0000' + value + '\u0000' + field));
if speed here matters consider stringbuilder

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
> +                    offsetIter.next();
should this just continue or throw an exception?

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
>                  log.error("Next failed: " + range, ioe);
not sure this should be caught

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
> +        } catch (InvalidProtocolBufferException e) {
probably don't want to catch this either

2022-07-26 14:08 UTC, FineAndDandy commented on warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
>  public class IteratorBuildingVisitorTest {
there are a bunch of @Ignore on these... do they need to stay that way?

2022-08-01 09:43 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/core/iterators/TermFrequencyIterator.java
> +                source.next();
The original code catches exceptions on initial seek, next calls, and when attempting to deserialize the value into a TermWeight object.

2022-08-01 09:50 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
> +                    offsetIter.next();
The original code catches exceptions

2022-08-01 09:50 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
>                  log.error("Next failed: " + range, ioe);
Original code catches exceptions

2022-08-01 09:50 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermOffsetPopulator.java
> +        } catch (InvalidProtocolBufferException e) {
Original code catches this

2022-08-01 09:52 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +    private boolean isTld = false;
Good catch, that is removed in the next commit

2022-08-01 09:55 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/core/iterators/key/TFKey.java
> +        return backing != null && nulls.size() >= 3;
`nulls` seems to be the common name for storing the null-delimiter indexes. What do you have in mind?

2022-08-01 09:58 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/functions/TermFrequencyList.java
>      public static String getEventId(Key key) {
The event id is `shard\0datatype\0uid`. I don't think it make sense for this feature to go into the DatawaveKey

2022-08-01 10:13 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +                        hits.add(new Text(datatype + '\u0000' + uid + '\u0000' + value + '\u0000' + field));
added in next commit

2022-08-01 10:40 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/postprocessing/tf/TermFrequencyHitFunction.java
> +            } else {
Ancestor queries set the `isTld` flag, so the correct ranges will still be built.

2022-08-01 11:03 UTC, apmoriarty commented on warehouse/query-core/src/test/java/datawave/query/jexl/visitors/IteratorBuildingVisitorTest.java
>  public class IteratorBuildingVisitorTest {
I'll update those tests where possible

2022-08-05 13:02 UTC, FineAndDandy approved these changes

2022-11-18 15:48 UTC, closed without merging