fixes #1673: Updates the whindex visitor to use the whindex creation …
NationalSecurityAgency/datawave pull request #1674
Opened 2022-08-16 13:20 UTC by jwomeara

…date to determine whether a whindex should be used.

This depends on the following change in the metadata-utils repo:
https://github.com/NationalSecurityAgency/datawave-metadata-utils/pull/12

2022-08-23 09:36 UTC, FineAndDandy requested changes, later dismissed

2022-08-23 09:36 UTC, FineAndDandy commented on warehouse/query-core/src/test/java/datawave/query/jexl/visitors/WhindexVisitorTest.java
> +        creationDateMap.put("NUT_SUNDAE", new Date(0));
can you add one test case which verifies that the dates are applied correctly? -1/0/+1

2022-10-13 14:33 UTC, jwomeara commented on warehouse/query-core/src/test/java/datawave/query/jexl/visitors/WhindexVisitorTest.java
> +        creationDateMap.put("NUT_SUNDAE", new Date(0));
I think I already covered this.  Check line 89 where I set the date for HOT_FUDGE_SUNDAE to something other than new Date(0)

2022-10-26 13:49 UTC, ivakegg approved these changes

2022-11-16 17:39 UTC, keith-ratcliffe approved these changes
LGTM

2022-11-16 19:57 UTC, merged