Update to hadoop 3.3.3
NationalSecurityAgency/datawave pull request #1777
Opened 2022-12-01 15:33 UTC by alerman

2022-12-01 15:55 UTC, apmoriarty approved these changes, later dismissed

2022-12-01 16:21 UTC, hlgp submitted a review, later dismissed

2022-12-02 12:41 UTC, jschmidt10 approved these changes, later dismissed

2022-12-02 16:18 UTC, ivakegg approved these changes, later dismissed

2022-12-05 16:08 UTC, keith-ratcliffe requested changes
Sorry to be late to the game. The web deployment failure in the quickstart reminds me that there are updates needed in this [module.xml](https://github.com/NationalSecurityAgency/datawave/blob/update-hadoop-version/web-services/deploy/application/src/main/wildfly/overlay/modules/org/apache/hadoop/common/main/module.xml) file for wildfly. Compare to what's in the new [version5.0 branch](https://github.com/NationalSecurityAgency/datawave/blob/release/version5.0/web-services/deploy/application/src/main/wildfly/overlay/modules/org/apache/hadoop/common/main/module.xml) (formerly feature/accumulo-2.1)

Also, I see that hadoop's [bootstrap.sh](https://github.com/NationalSecurityAgency/datawave/blob/update-hadoop-version/contrib/datawave-quickstart/bin/services/hadoop/bootstrap.sh#L6) in the quickstart is still pulling the old version of hadoop

2022-12-05 19:23 UTC, keith-ratcliffe commented
Also, you may have already found that when 3.3.3 is deployed, a new issue surfaces the classpath setup for log4j in 1.9's `bin/accumulo`. If not...

It's because the script tries this:
```
LOG4J_JAR=$(find -H "${HADOOP_PREFIX}/lib" "${HADOOP_PREFIX}"/share/hadoop/common/lib -regex '.*/log4j-[0-9.]*[.]jar$' -print 2>/dev/null | head -1)
```
...but it needs to do this instead:
```
LOG4J_JAR=$(find -H "${HADOOP_HOME}/lib" "${HADOOP_HOME}"/share/hadoop/common/lib -regex '.*/reload4j-[0-9.]*[.]jar$' -print 2>/dev/null | head -1)
```

2022-12-05 21:14 UTC, keith-ratcliffe commented
> Also, you may have already found that when 3.3.3 is deployed, a new issue surfaces with the classpath setup for log4j in 1.9's `bin/accumulo`

The log4j issue can be fixed by updating accumulo's [bootstrap.sh](https://github.com/NationalSecurityAgency/datawave/blob/update-hadoop-version/contrib/datawave-quickstart/bin/services/accumulo/bootstrap.sh#L35) to download the stock 1.10.2 tarball, instead of the 1.9 that is currently being pulled

2022-12-06 04:04 UTC, keith-ratcliffe approved these changes

2022-12-06 04:06 UTC, keith-ratcliffe approved these changes

2022-12-06 11:17 UTC, apmoriarty approved these changes

2022-12-14 17:29 UTC, ivakegg approved these changes

2023-01-27 17:41 UTC, merged