WIP: Removing datatype filter from termfrequencyindexiterator
NationalSecurityAgency/datawave pull request #1886
Opened 2023-03-14 17:46 UTC by avgAGB

2023-03-27 18:31 UTC, ivakegg reviewed
Why exactly are we removing the dataType filter?

2023-03-28 11:49 UTC, avgAGB commented
> Why exactly are we removing the dataType filter?

The description of the ticket states that the TermFrequencyIndexIterator is scanning the TF column family, and because the datatype is built into the scan range no datatype filter needs to be applied.

2023-03-29 16:26 UTC, matthpeterson approved these changes, later dismissed
It appears that datatypeFilter was never read.  Looks good to me.

2023-03-30 18:51 UTC, apmoriarty approved these changes, later dismissed

2023-04-13 16:40 UTC, jwomeara requested changes
I get that the field index range contains the type, so adding type filtering at this level doesn't make sense, but are we verifying at a higher level that we don't generate ranges against disallowed types?  i.e. if someone sets a type filter upstream, are we ensuring that we don't create term frequency ranges against those types?  i suspect not, but maybe we should.

2023-04-13 16:40 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/iterator/builder/TermFrequencyIndexBuilder.java
If we're not using this.datatypeFilter anymore, let's remove it from the class completely.

2023-04-17 11:18 UTC, avgAGB commented on warehouse/query-core/src/main/java/datawave/query/iterator/builder/TermFrequencyIndexBuilder.java
Done, removed from the latest commit.

2023-04-17 12:34 UTC, avgAGB commented
> I get that the field index range contains the type, so adding type filtering at this level doesn't make sense, but are we verifying at a higher level that we don't generate ranges against disallowed types? i.e. if someone sets a type filter upstream, are we ensuring that we don't create term frequency ranges against those types? i suspect not, but maybe we should.

To clarify a bit, did you want to verify that if someone sets a type filter on a query that the term frequency fields that are retrieved are the ones that are part of the type filter set?

2023-04-17 16:08 UTC, jwomeara commented
> > I get that the field index range contains the type, so adding type filtering at this level doesn't make sense, but are we verifying at a higher level that we don't generate ranges against disallowed types? i.e. if someone sets a type filter upstream, are we ensuring that we don't create term frequency ranges against those types? i suspect not, but maybe we should.
> 
> To clarify a bit, did you want to verify that if someone sets a type filter on a query that the term frequency fields that are retrieved are the ones that are part of the type filter set?

I believe that's what I'm saying, yes.  If a user specified only wanting to query against a specific set of types, we should make sure that we don't generate TF ranges against any types but those allowed by the user.

2023-07-17 17:51 UTC, avgAGB commented
> > > I get that the field index range contains the type, so adding type filtering at this level doesn't make sense, but are we verifying at a higher level that we don't generate ranges against disallowed types? i.e. if someone sets a type filter upstream, are we ensuring that we don't create term frequency ranges against those types? i suspect not, but maybe we should.
> > 
> > 
> > To clarify a bit, did you want to verify that if someone sets a type filter on a query that the term frequency fields that are retrieved are the ones that are part of the type filter set?
> 
> I believe that's what I'm saying, yes. If a user specified only wanting to query against a specific set of types, we should make sure that we don't generate TF ranges against any types but those allowed by the user.

This one slipped through the cracks for me, but I managed to verify with test queries that even with these removed, the metadata helper will only build a set of term frequency fields based on the filters that the user specifies. I'll clean up the merge conflicts and request for some reviews again when I get an opportunity.

2023-07-18 10:39 UTC, apmoriarty approved these changes

2023-07-26 18:12 UTC, jwomeara approved these changes

2023-07-26 18:23 UTC, merged