Update projections contract
NationalSecurityAgency/datawave pull request #1918
Opened 2023-04-05 14:10 UTC by nonessentialprototype

This Closes #1512  and does the following.

1.  Projection, KeyProjection, DocumentProjection has no default constructor now, and take the Set of projections and a new enum with the type of projection (`INCLUDES`, or `EXCLUDES`)
2.  Projections doesn't throw any exceptions anymore.
3. EventDataQueryFieldFilter does not extend KeyProjection anymore (caused a bad code smell with the constructor) and just holds a KeyProjection locally now.

2023-04-06 11:05 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
>          return projection;
These two lines could be collapsed.

2023-04-06 11:46 UTC, apmoriarty submitted a review, later dismissed

2023-04-14 19:02 UTC, jwomeara requested changes
Looks good.  Just a few minor nits.

2023-04-14 19:02 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
> -            String msg = "Configured to use projection, but no whitelist or blacklist was provided";
If we're changing the log message, is there a reason not to change the variable names too?

2023-04-14 19:02 UTC, jwomeara commented on warehouse/query-core/src/main/java/datawave/query/predicate/KeyProjection.java
>      protected Projection projection;
Intellij wants this to be private since the class is final.

2023-04-14 19:02 UTC, jwomeara commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/TermFrequencyAggregatorTest.java
> +import static org.junit.Assert.*;
Please update your IDE to not replace imports with * imports.

2023-06-05 19:03 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryIterator.java
> -            String msg = "Configured to use projection, but no whitelist or blacklist was provided";
Fixed.

2023-06-05 19:04 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/predicate/KeyProjection.java
>      protected Projection projection;
Fixed.

2023-06-05 19:04 UTC, MiguelRicardos commented on warehouse/query-core/src/test/java/datawave/query/jexl/functions/TermFrequencyAggregatorTest.java
> +import static org.junit.Assert.*;
Fixed.

2023-06-13 16:32 UTC, jwomeara submitted a review, later dismissed

2023-06-14 09:23 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/iterator/facets/DynamicFacetIterator.java
> +    Map<String,String> documentIteratorOptions;
nice catch

2023-06-14 09:28 UTC, apmoriarty approved these changes, later dismissed
LGTM

2023-06-15 13:45 UTC, MiguelRicardos commented
Per conversation, closing merge request.

2023-06-15 13:45 UTC, closed without merging