Remove SeekingQueryPlanner code.
NationalSecurityAgency/datawave pull request #1931
Opened 2023-04-14 12:50 UTC by jack-gitdev

2023-04-14 12:54 UTC, apmoriarty requested changes

2023-04-14 12:54 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/config/LookupUUIDTune.java
> +                rsq.setFiNextSeek(maxKeysBeforeSeek);
`maxFieldHitsBeforeSeek` and `maxKeysBeforeSeek` should be removed along with any getters/setters. 

Then you can set the fi and event seek values from lines 34-37

2023-04-14 13:11 UTC, apmoriarty approved these changes, later dismissed

2023-04-17 17:22 UTC, avgAGB submitted a review, later dismissed

2023-04-18 19:41 UTC, jwomeara reviewed
I'm guessing the answer is "because we don't use it", but why are we removing this?

2023-04-19 10:22 UTC, apmoriarty commented
> I'm guessing the answer is "because we don't use it", but why are we removing this?

The functionality of the SeekingQueryPlanner was pushed into the DefaultQueryPlanner in these two merge requests. This merge request deals with cleaning up the now-dead code.
- https://github.com/NationalSecurityAgency/datawave/pull/1869
- https://github.com/NationalSecurityAgency/datawave/pull/1883

2023-04-19 13:52 UTC, jwomeara commented
> > I'm guessing the answer is "because we don't use it", but why are we removing this?
> 
> The functionality of the SeekingQueryPlanner was pushed into the DefaultQueryPlanner in these two merge requests. This merge request deals with cleaning up the now-dead code.
> 
> * [More ways to configure seeking in the QueryIterator #1869](https://github.com/NationalSecurityAgency/datawave/pull/1869)
> * [Integrate seeking configuration changes #1883](https://github.com/NationalSecurityAgency/datawave/pull/1883)

Perfect!  That's the piece of information I was missing.

2023-04-19 13:53 UTC, jwomeara submitted a review, later dismissed

2023-06-15 16:42 UTC, apmoriarty approved these changes, later dismissed

2023-06-15 17:06 UTC, avgAGB submitted a review, later dismissed

2023-07-25 00:44 UTC, hlgp approved these changes

2023-07-25 18:42 UTC, alerman approved these changes

2023-07-25 18:53 UTC, apmoriarty approved these changes

2023-07-26 19:25 UTC, merged