change deprecated BasicParser to DefaultParser
NationalSecurityAgency/datawave pull request #1947
Opened 2023-05-04 13:06 UTC by tomnelson

I'm updating calls to deprecated code with a goal of updating the accumulo calls. I plan to make several small PRs so that ongoing code inspection is less cluttered.

2023-05-05 18:20 UTC, keith-ratcliffe requested changes

2023-05-05 18:20 UTC, keith-ratcliffe commented on warehouse/ops-tools/index-validation/src/main/java/datawave/index/validation/AccumuloIndexAgeDisplay.java
> +import org.apache.commons.cli.*;
A minor nit, but the reigning view on wildcard imports for DW is to avoid them.
Other than that, this PR is good to go

2023-05-06 01:22 UTC, keith-ratcliffe approved these changes

2023-05-12 02:04 UTC, jwomeara approved these changes

2023-05-19 15:44 UTC, merged