WIP: issue-1229: Save shard-specific query subplans to metrics
NationalSecurityAgency/datawave pull request #2027
Opened 2023-07-07 14:15 UTC by foster33

Aims to add query subplans to the metrics for the query. Also will make the subplans viewable via the metrics endpoint.

Fixes #1229

2023-07-17 14:48 UTC, ivakegg commented on web-services/query/src/main/java/datawave/webservice/query/metric/QueryMetricsBean.java
> +            return remoteQueryMetricService.id(id);
This remote call would return the query metrics page, not the subplans.  There needs to be a remoteQueryMetricService.subplan that delegates to the query metrics microservice.  The query metrics microservice would need to implement a subplan endpoint similar to how you have done it here.

2023-09-06 19:52 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/metrics/ShardTableQueryMetricHandler.java
> +                        subplans.put(arr[0], arr[1]);
probably need a check that arr is of size 2 here

2023-09-12 15:58 UTC, billoley requested changes

2023-09-12 15:58 UTC, billoley commented on contrib/datawave-quickstart/bin/services/accumulo/bootstrap.sh
> +DW_ACCUMULO_DIST_URI="${DW_ACCUMULO_DIST_URI:-http://archive.apache.org/dist/accumulo/2.1.1/accumulo-2.1.1-bin.tar.gz}"
Change from accumulo 2.1.0 to 2.1.1 already in integration

2023-09-12 15:58 UTC, billoley commented on pom.xml
> +        <version.accumulo>2.1.1</version.accumulo>
Change from accumulo 2.1.0 to 2.1.1 already in integration

2023-09-12 15:58 UTC, billoley commented on pom.xml
> +        <version.microservice.query-metric-api>2.1.1-1229</version.microservice.query-metric-api>
Will have to release query-metric-api 2.1.1 first, then change this to 2.1.1

2023-09-12 15:58 UTC, billoley commented on warehouse/query-core/src/main/java/datawave/query/metrics/ShardTableQueryMetricHandler.java
> +    public QueryMetricsSubplanResponse subplan(String user, String queryId, DatawavePrincipal datawavePrincipal) {
Avoid code duplication by passing parameters, or blacklisted fields, or another way

2023-12-19 16:11 UTC, foster33 commented
There are currently test failures within VisitorFunctionTest relating to EasyMock expectations.

2025-04-11 15:13 UTC, closed without merging