Standardize Handling of FieldSets
NationalSecurityAgency/datawave pull request #2038
Opened 2023-07-17 12:03 UTC by apmoriarty

Change Set
- fieldset serialization is now standardized
- fieldset reduction is now standardized and options exist for one reduction at the end of query planning or reduction applied on a per-shard basis (for use cases where range stream reduction is applied)
- fieldset compression inspired by https://github.com/NationalSecurityAgency/datawave/pull/1975 was added and is compatible with either mode of fieldset reduction. Note: compression only applied to indexed fields, index-only fields, and composite fields.

2023-07-17 12:41 UTC, ivakegg requested changes

2023-07-17 12:41 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
>          return reduceQueryFields;
Should we be dropping this field and instead call one of the getters below?

2023-07-17 12:53 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/config/ShardQueryConfiguration.java
>          return reduceQueryFields;
I don't believe so. If a user has this option configured and we suddenly delegate to a completely new option that is not yet configured this pr would become a breaking change.

2023-09-25 15:46 UTC, apmoriarty commented
We did extensive testing of this feature and found no cases where compressing the field sets led to an increase in performance.

2023-09-25 15:46 UTC, closed without merging