Refactoring poms in warehouse module
NationalSecurityAgency/datawave pull request #2073
Opened 2023-08-26 17:31 UTC by avgAGB

2023-08-28 11:59 UTC, alerman requested changes

2023-08-28 11:59 UTC, alerman commented on pom.xml
> +                <version>3.3.3</version>
You added version 3.3.5 everywhere else. Move the versions up to the top level pom and make a property to make our lives easier when we update.

2023-08-28 15:55 UTC, avgAGB commented on pom.xml
> +                <version>3.3.3</version>
Ah thanks. Will fix this.

2023-09-05 15:34 UTC, alerman submitted a review, later dismissed

2023-09-05 18:52 UTC, keith-ratcliffe submitted a review, later dismissed

2023-09-19 14:59 UTC, mineralntl submitted a review, later dismissed

2023-09-20 18:14 UTC, awrigh11 approved these changes, later dismissed

2023-09-22 17:55 UTC, mineralntl approved these changes

2023-09-25 16:31 UTC, matthpeterson approved these changes

2023-09-25 16:32 UTC, merged