Feature/fi reindex
NationalSecurityAgency/datawave pull request #2152
Opened 2023-10-30 05:05 UTC by FineAndDandy

2023-10-30 10:11 UTC, apmoriarty commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +        // job.output.table.names must be set or this won't work
Does this mean the job will execute but not do the correct operation? Or will the job fail with an illegal arg exception?

2023-10-30 10:35 UTC, apmoriarty commented on warehouse/ingest-scripts/src/main/resources/bin/ingest/shard-reindex.sh
> +# specifying no partitioning argument will default to the MultiTableRangePartitioner
Maybe print a warning if no partition arg is found?

2023-10-30 15:31 UTC, hlgp commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
> +    public static Set<String> setupAndCacheTables(Configuration conf, boolean createTables)
nice

2023-11-29 12:55 UTC, ivakegg commented on warehouse/ingest-scripts/src/main/resources/bin/ingest/shard-reindex.sh
> +
A comment at the top denoting how to use this script with an example would be nice.

2023-11-29 13:19 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +        @Parameter(names = "--inputFiles", description = "When set these files will be used for the job", required = false)
comma delimited ?
directory?

2023-11-29 13:22 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +        @Parameter(names = "--workDir", description = "Temporary work location in hdfs", required = true)
specify directory should exist

2023-11-29 13:22 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +        @Parameter(names = "--outputDir", description = "output directory", required = true)
specify directory cannot be pre-created.

2023-11-29 13:25 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +            if (WritableComparator.compareBytes(cf, 0, 3, FI_START_BYTES, 0, FI_START_BYTES.length) != 0) {
Need to check the lenth of cf first.  There will be keys in the shard table where the cf is less than 3 and this will throw an exception.

2023-11-29 13:29 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +            if (WritableComparator.compareBytes(cf, 0, 3, FI_START_BYTES, 0, FI_START_BYTES.length) != 0) {
Also shouldn't that first 3 also be FI_START_BYTES.length ?

2023-11-29 13:30 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +            if (lastFiBytes == null || WritableComparator.compareBytes(cf, 4, cf.length - 4, lastFiBytes, 4, lastFiBytes.length - 4) != 0) {
again, may need to check the cf length first.

2023-11-29 13:38 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +            if (lastFiBytes == null || WritableComparator.compareBytes(cf, 4, cf.length - 4, lastFiBytes, 4, lastFiBytes.length - 4) != 0) {
FI_START_BYTES.length +1 instead of 4 ?

2023-11-29 13:39 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +                field = new String(cf, 3, cf.length - 3);
FI_START_BYTES.length instead of 3

2023-11-29 13:51 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/ShardReindexJob.java
> +
Need to set the context on the MultiTableRangePartitioner here (see line 403 of the EventMapper)

2023-11-29 14:44 UTC, ivakegg requested changes
See comments

2023-11-30 15:04 UTC, ivakegg approved these changes

2023-11-30 15:23 UTC, apmoriarty approved these changes

2023-11-30 16:00 UTC, merged