WIP: incorporating the similarity scoring refactor
NationalSecurityAgency/datawave pull request #2236
Opened 2024-01-26 22:40 UTC by drewfarris

2024-02-21 15:00 UTC, MiguelRicardos requested changes

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
> +    /** We'll toss out any matches that have scores less than this value. If set to 0 or less we'll keep all hashes */
So a value of -1 would be the same result as 0?

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
> +     * @return the minimum score threshold specified in the query parameter, 0 if none is set or the value of the parameter is outside of the bounds 0 &gt;= n
0 &gt;= n
     *         &gt;= 100.
 
 you mean:
 
 0 <= n <= 100 ?
 
 Locally it's rendering as ```&gt;=n```

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
> +        // +++//thPkK 3:3:yionv//thPkKlDtn/rXScG2/uDlhl2UE9FQEul/lldDpZflsup:6v/lhPkKlDtt/6TIPFQEqRDpZ+up []
Can you add a link that explains this format as a comment in the code just for future archeology?

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryTransformer.java
> +        FieldBase f = responseObjectFactory.getField();
can you use a more descriptive variable name than f?

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryTransformer.java
> +        for (Object o : resultList) {
can you use a more descriptive variable name than o, something like ```result``` to make it a little easier to follow?

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/ScoredSSDeepPair.java
> +        int result = queryHash != null ? queryHash.hashCode() : 0;
Any reason not to do:
```
    return Objects.hash(queryHash, matchingHash, weightedScore, overlapScore);
```

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/query-core/src/test/java/datawave/query/tables/ssdeep/SSDeepIngestQueryTest.java
> +        SSDeepTestUtil.assertSSDeepSimilarityMatch(testSSDeep, testSSDeep, "38", "100", observedEvents);
Just curious of why it went from a double to an int.

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/ssdeep-common/src/main/java/datawave/util/ssdeep/SSDeepHashEditDistanceScorer.java
> +    public int apply(SSDeepHash signature1, SSDeepHash signature2) {
Why are you using longs in this method if the getChunkSize returns an int?

2024-02-21 15:00 UTC, MiguelRicardos commented on warehouse/ssdeep-common/src/main/java/datawave/util/ssdeep/SSDeepHashEditDistanceScorer.java
> +            score = scoreChunks(s1chunk, s2doubleChunk, chunkSize1);
Same with scoreChunks returning int instead of long?

2024-02-21 15:02 UTC, MiguelRicardos commented
Overall looks good. Couple comments. Builds successfully. Formatting matches.

2024-02-22 20:17 UTC, drewfarris commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
> +    /** We'll toss out any matches that have scores less than this value. If set to 0 or less we'll keep all hashes */
Yes. In this context negative scores aren't a thing.

2024-02-22 20:19 UTC, drewfarris commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepScoringFunction.java
> +     * @return the minimum score threshold specified in the query parameter, 0 if none is set or the value of the parameter is outside of the bounds 0 &gt;= n
Yeah, it should be `&lt;` not `&gt;`

2024-02-22 20:22 UTC, drewfarris commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryTransformer.java
> +        for (Object o : resultList) {
'o' is used exactly twice here as a placeholder for a cast into an EventBase named `event`. So, I don't think changing the name from `o` to `result` be less confusing.

2024-02-22 20:28 UTC, drewfarris commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/ScoredSSDeepPair.java
> +        int result = queryHash != null ? queryHash.hashCode() : 0;
Nope

2024-02-22 20:29 UTC, drewfarris commented on warehouse/query-core/src/test/java/datawave/query/tables/ssdeep/SSDeepIngestQueryTest.java
> +        SSDeepTestUtil.assertSSDeepSimilarityMatch(testSSDeep, testSSDeep, "38", "100", observedEvents);
The scores are never double/floating point, so there was no need to use one to represent them. This was something that was improved over the original implementation.

2024-02-22 20:31 UTC, drewfarris commented on warehouse/ssdeep-common/src/main/java/datawave/util/ssdeep/SSDeepHashEditDistanceScorer.java
> +    public int apply(SSDeepHash signature1, SSDeepHash signature2) {
They should be ints.

2024-02-22 20:31 UTC, drewfarris commented on warehouse/ssdeep-common/src/main/java/datawave/util/ssdeep/SSDeepHashEditDistanceScorer.java
> +            score = scoreChunks(s1chunk, s2doubleChunk, chunkSize1);
Same, they should be ints

2024-02-27 17:03 UTC, cogross approved these changes, later dismissed

2024-02-27 19:17 UTC, sparkyy34 commented on warehouse/query-core/src/main/java/datawave/query/tables/ssdeep/SSDeepSimilarityQueryLogic.java
> +        log.info("Pre-processing " + queries.size() + " SSDeepHash queries");
duplicate of line 116?

2024-02-28 13:15 UTC, MiguelRicardos submitted a review, later dismissed

2024-02-28 18:23 UTC, sparkyy34 approved these changes
looks good to me

2024-02-29 14:36 UTC, MiguelRicardos approved these changes

2024-02-29 20:00 UTC, merged