re #2239: clear the document before exiting the method.
NationalSecurityAgency/datawave pull request #2240
Opened 2024-01-30 18:02 UTC by d-hwang

empty keys are expected in some cases

2024-01-30 18:06 UTC, drewfarris submitted a review, later dismissed

2024-01-30 18:09 UTC, FineAndDandy requested changes
can we have a bare bones unit test for this issue?

2024-01-30 18:12 UTC, ivakegg submitted a review, later dismissed

2024-01-30 18:14 UTC, ivakegg approved these changes, later dismissed

2024-01-30 18:33 UTC, drewfarris approved these changes, later dismissed

2024-01-30 22:14 UTC, apmoriarty submitted a review, later dismissed

2024-01-30 23:38 UTC, hlgp approved these changes, later dismissed

2024-01-31 14:53 UTC, drewfarris approved these changes

2024-01-31 17:10 UTC, jack-gitdev approved these changes

2024-01-31 17:54 UTC, merged

2024-01-31 18:13 UTC, FineAndDandy commented
Thanks @apmoriarty for adding the unit test