fixes #2303: composite and filtered query logics
NationalSecurityAgency/datawave pull request #2319
Opened 2024-03-20 20:41 UTC by ivakegg

* Updated to not drop filtered query logics allowing appropriate failure and success scenarios

2024-03-29 12:10 UTC, FineAndDandy requested changes

2024-03-29 12:10 UTC, FineAndDandy commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                        logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
can be removed if moved up

2024-03-29 12:10 UTC, FineAndDandy commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                    logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
can be removed if moved up

2024-03-29 12:10 UTC, FineAndDandy commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                        logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
move this above the if/else block to reduce redundancy

2024-03-29 18:29 UTC, ivakegg commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                        logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
done

2024-03-29 18:29 UTC, ivakegg commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                    logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
done

2024-03-29 18:29 UTC, ivakegg commented on web-services/query/src/main/java/datawave/webservice/query/logic/composite/CompositeQueryLogic.java
> +                        logicQueryStringBuilder.append("( ( logic = '").append(logicName).append("' )");
done

2024-04-01 17:17 UTC, FineAndDandy approved these changes

2024-04-02 15:44 UTC, apmoriarty approved these changes

2024-04-02 15:45 UTC, merged