Added most recent equivalent unique functions
NationalSecurityAgency/datawave pull request #2339
Opened 2024-04-05 21:13 UTC by ivakegg

* Simply add MOST_RECENT_ in front of the function name

2024-04-08 09:17 UTC, apmoriarty approved these changes, later dismissed

2024-04-09 00:06 UTC, avgAGB approved these changes, later dismissed

2024-04-10 19:30 UTC, MiguelRicardos requested changes
Builds find. Looks good. Just one small change on a comment.

2024-04-10 19:30 UTC, MiguelRicardos commented on warehouse/query-core/src/main/java/datawave/query/language/functions/jexl/MostRecentUniqueByHour.java
> + * {@code #MOST_RECENT_UNIQUE(field[DAY])}.
you mean ```feild[HOUR]``` ?

2024-04-10 19:40 UTC, MiguelRicardos approved these changes

2024-04-11 12:37 UTC, avgAGB approved these changes

2024-04-16 13:38 UTC, apmoriarty approved these changes

2024-04-18 13:02 UTC, merged