Add logging of query IDs via QueryLogIterator class
NationalSecurityAgency/datawave pull request #2409
Opened 2024-06-07 19:05 UTC by SethSmucker

- Create QueryLogIterator class that logs a query's ID to the TServer logs
- Add QueryLogIterator to DefaultQueryPlanner
- Add tserver.logging.active to QueryParameters, used to turn logging on and off
- Add tests for QueryLogIterator and TServerLogging

Resolves #2305

2024-06-11 11:11 UTC, jschmidt10 commented on warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
> +import datawave.query.iterator.QueryLogIterator;
This import is unused.

2024-06-11 11:15 UTC, jschmidt10 commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryLogIterator.java
> +            logStartOf("init()");
Seems like this should be the first thing called in the function here. Also there is no delegation to the `source.init()`.

2024-06-11 14:00 UTC, foster33 commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryOptions.java
There are no actual changes here, so this class can probably be reverted.

2024-06-11 18:18 UTC, avgAGB commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryLogIterator.java
> +    public QueryLogIterator() {}
Could this be pruned out if it isn't being used?

2024-06-12 17:21 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
> +    public static final String TSERVER_LOGGING_ACTIVE = "tserver.logging.active";
Please move this constant to the QueryOptions class instead.  QueryParameters are for parameters specified by users when submitting queries.  This is purly used as an option on the query log iterator.

2024-06-12 18:34 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/iterator/QueryLogIterator.java
> +            logStartOf("init()");
The tserver iterator setup will be calling the source.init with the options specific to that iterator.  No need to call source.init().

2024-06-12 18:38 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/QueryParameters.java
> +    public static final String TSERVER_LOGGING_ACTIVE = "tserver.logging.active";
Actually, now that I look at it you are setting this as a iterator option as well as pulling it out of the query parameters.  I don't believe the user submitting the query should be able to turn logging off and on.  That should be done when the query logic is being created (see QueryLogicFactory.xml).  You may want to add a line in there.  I think this constant should go away, and the default query planner should optionally setup the QueryLogIterator if that boolean is true in the configuration.

2024-06-12 18:42 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
> +        List<IteratorSetting> iteratorSettings = logCfg == null ? Collections.singletonList(cfg) : Lists.newArrayList(cfg, logCfg);
We should only be adding the logCfg if config.isTserverLoggingActive().

2024-06-12 18:43 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/planner/DefaultQueryPlanner.java
> +        List<IteratorSetting> iteratorSettings = logCfg == null ? Collections.singletonList(cfg) : Lists.newArrayList(cfg, logCfg);
Optionally avoid creating the logCfg altogether if config.IsTserverLoggingActive() == false;.,

2024-06-12 18:47 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/config/ShardQueryConfigurationTest.java
> +        defaultValues.put("tserverLoggingActive", false);
I think the default should be true

2024-06-12 18:48 UTC, ivakegg commented on warehouse/query-core/src/test/java/datawave/query/tables/ShardQueryLogicTest.java
> +
This is not much of a test....

2024-06-12 18:48 UTC, ivakegg requested changes
See comments

2024-06-20 20:21 UTC, closed without merging

2024-06-20 20:22 UTC, SethSmucker commented
Superseded by #2428, all changes suggested have been added there. That PR pulls directly from my fork instead of using a middle-man branch between my fork's branch and upstream/integration.