Replace deprecated OptionBuilder with Option.builder()
NationalSecurityAgency/datawave pull request #2488
Opened 2024-07-31 20:33 UTC by SethSmucker

The following classes have been updated to use Option.builder() instead of the deprecated class OptionBuilder:
1. datawave.ingest.util.AccumuloCliOptions
2. datawave.ingest.util.GenerateMultipleNumShardCacheFile
3. datawave.ingest.util.GenerateSplitFile
4. datawave.metrics.config.MetricOptions

part of #2443

2024-08-01 12:10 UTC, foster33 commented on warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateMultipleNumShardsCacheFile.java
> +        options.addOption(Option.builder(CONFIG_SUFFIEX_OVERRIDE).argName("Config Suffix").hasArg().required().desc("Config file suffix").build());
Seems like the original code had a typo in `CONFIG_SUFFIEX_OVERRIDE`. Maybe change it to `CONFIG_SUFFIX_OVERRIDE` ?

2024-08-05 11:31 UTC, avgAGB commented
Does it make sense to remove the OptionBuilderTest unit tests too?

2024-09-04 15:31 UTC, ivakegg submitted a review, later dismissed

2024-09-06 20:15 UTC, ivakegg approved these changes

2024-09-12 11:44 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/util/GenerateMultipleNumShardsCacheFile.java
> +        options.addOption(Option.builder(CONFIG_SUFFIX_OVERRIDE).argName("Config Suffix").hasArg().required().desc("Config file suffix").build());
This one is not required.  Caught this as it broke in integration testing.

2024-09-12 11:45 UTC, ivakegg requested changes
double check what is required and what is not in terms of options.

2024-10-09 19:57 UTC, ivakegg approved these changes, later dismissed

2024-10-30 11:04 UTC, apmoriarty approved these changes, later dismissed

2025-07-08 10:28 UTC, apmoriarty approved these changes

2025-07-08 12:07 UTC, drewfarris approved these changes

2025-07-14 10:56 UTC, merged