Replace deprecated INSTANCE_DFS_URI/DIR with INSTANCE_VOLUMES
NationalSecurityAgency/datawave pull request #2491
Opened 2024-08-01 15:51 UTC by SethSmucker

INSTANCE_DFS_DIR and INSTANCE_DFS_URI were deprecated, both being replaced with INSTANCE_VOLUMES

part of https://github.com/NationalSecurityAgency/datawave/issues/2443

2024-08-05 10:18 UTC, avgAGB submitted a review, later dismissed

2024-09-04 15:36 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/mr/bulk/MultiRfileInputformat.java
> +                dfsUriMap.put(tableId, instOps.getSystemConfiguration().get(Property.INSTANCE_VOLUMES.getKey()));
So if the dfsDirMap is no longer used, then we should update those other places where we check its contents.

2024-09-04 15:37 UTC, ivakegg requested changes
see comment

2024-09-06 20:19 UTC, ivakegg commented
ok, now I need to actually test this out to make sure we are good.

2024-09-06 20:23 UTC, ivakegg approved these changes

2024-09-12 13:26 UTC, apmoriarty approved these changes

2024-09-12 18:23 UTC, merged