Use stopwatch for ingestjob to make timing a bit cleaner
NationalSecurityAgency/datawave pull request #2517
Opened 2024-08-14 22:46 UTC by alerman

2024-08-15 11:17 UTC, apmoriarty approved these changes

2024-08-16 11:33 UTC, FineAndDandy requested changes

2024-08-16 11:33 UTC, FineAndDandy commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
> +        long start = System.currentTimeMillis();
never referenced

2024-08-16 11:33 UTC, FineAndDandy commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
>          long stop = System.currentTimeMillis();
never referenced

2024-08-16 12:08 UTC, alerman commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
> +        long start = System.currentTimeMillis();
see call to writeStats on line 532

2024-08-16 12:08 UTC, alerman commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/IngestJob.java
>          long stop = System.currentTimeMillis();
see call to writeStats on line 532

2024-08-19 11:26 UTC, avgAGB approved these changes

2024-08-22 14:17 UTC, FineAndDandy approved these changes

2024-08-23 21:53 UTC, hlgp approved these changes

2024-10-07 10:55 UTC, merged