Replace nonpublic Acumulo DefaultFormatter
NationalSecurityAgency/datawave pull request #2525
Opened 2024-08-22 16:13 UTC by SethSmucker

`org.apache.accumulo.core.util.format.DefaultFormatter` is not part of Accumulo's public API. `DefaultFormatter.formatEntry()`is the only part of the class used in Datawave.

Replace the references of to Accumulo's `DefaultFormatter` with code that functions the same without the reference.

part of https://github.com/NationalSecurityAgency/datawave/issues/2443

2024-09-04 16:00 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/mr/bulk/BulkInputFormat.java
> +                        Key key = entry.getKey();
Can we simply reuse currentK from above?

2024-09-04 16:01 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/mr/bulk/BulkInputFormat.java
> +                        Value value = entry.getValue();
Can we simply reuse currentV from above?

2024-09-04 16:01 UTC, ivakegg requested changes
see comments

2024-09-06 20:22 UTC, ivakegg approved these changes

2024-09-12 13:26 UTC, apmoriarty approved these changes

2024-09-12 18:23 UTC, merged