Replace nonpublic Accumulo ColumnSet
NationalSecurityAgency/datawave pull request #2534
Opened 2024-08-26 15:23 UTC by SethSmucker

ColumnSet is not part of Accumulo's public API. encode/decodeColumns are the only part of the class used in Datawave.

Replace the references of to Accumulo's ColumnSet with code that functions the same without the reference.

part of https://github.com/NationalSecurityAgency/datawave/issues/2443

2024-08-26 23:32 UTC, avgAGB submitted a review, later dismissed

2024-09-04 16:40 UTC, ivakegg commented on warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/reduce/AggregatingReducer.java
>  @SuppressWarnings("deprecation")
Can we remove the suppress warnings?

2024-09-04 16:44 UTC, ivakegg approved these changes, later dismissed

2024-09-05 00:01 UTC, avgAGB submitted a review, later dismissed

2024-09-12 18:25 UTC, ivakegg approved these changes

2024-09-23 16:41 UTC, apmoriarty approved these changes

2024-10-16 13:15 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/util/ColumnSetUtil.java
> +    public static Pair<Text,Text> decodeColumns(String columns) {
Lets also avoid using Pair here (part of private api).  Use AbstractMap.SimpleEntry instead please

2024-10-16 13:15 UTC, ivakegg requested changes
One more update required.

2024-10-16 18:06 UTC, ivakegg commented
Actualy, this is already handled in #2423 so I am going to close this one.  My apologies.

2024-10-16 18:06 UTC, closed without merging