Replace nonpublic Accumulo IterationInterruptedException
NationalSecurityAgency/datawave pull request #2539
Opened 2024-08-27 18:56 UTC by SethSmucker

IterationInterruptedException is not part of Accumulo's public API.

Create IterationInterruptedException class in DataWave, replacing Accumulo's version.

part of https://github.com/NationalSecurityAgency/datawave/issues/2443

2024-08-28 11:25 UTC, avgAGB approved these changes, later dismissed

2024-08-28 13:36 UTC, foster33 submitted a review, later dismissed

2024-08-29 14:46 UTC, alerman requested changes

2024-08-29 14:46 UTC, alerman commented on warehouse/core/src/main/java/datawave/iterators/IterationInterruptedException.java
> +public class IterationInterruptedException extends RuntimeException {
I might suggest customizing the name slightly to avoid IDE's pulling in accumulo's import of the class of the same name to avoid confusion later.

2024-09-04 16:46 UTC, ivakegg commented on warehouse/core/src/main/java/datawave/iterators/IterationInterruptedException.java
> +public class IterationInterruptedException extends RuntimeException {
+1

2024-09-06 20:23 UTC, ivakegg requested changes
See Adam's comment

2024-09-09 15:47 UTC, SethSmucker commented
> See Adam's comment

Is it still too close? I changed it from `IterationInterruptedException` to `IterationInterruptException`. Might be a bit confusing if they're this close, what do you think?

2024-09-10 14:38 UTC, ivakegg commented
> > See Adam's comment
> 
> Is it still too close? I changed it from `IterationInterruptedException` to `IterationInterruptException`. Might be a bit confusing if they're this close, what do you think?

Now that I am looking one layer deeper, I realize that we were throwing that exception because we are implementing InterruptibleIterator which is an accumulo class.  Is that class part of the public API?  If so then we need to push for the original IteratorInterruptedException to be part of the public api.  Can you push that question over to the accumulo group please?

2024-09-13 15:42 UTC, ddanielr commented
> > > See Adam's comment
> > 
> > 
> > Is it still too close? I changed it from `IterationInterruptedException` to `IterationInterruptException`. Might be a bit confusing if they're this close, what do you think?
> 
> Now that I am looking one layer deeper, I realize that we were throwing that exception because we are implementing InterruptibleIterator which is an accumulo class. Is that class part of the public API? If so then we need to push for the original IteratorInterruptedException to be part of the public api. Can you push that question over to the accumulo group please?

@ivakegg the `InterruptibleIterator` is not in the list of iterators in the [accumulo public API](https://www.javadoc.io/static/org.apache.accumulo/accumulo-core/2.1.3/org/apache/accumulo/core/iterators/package-summary.html) 
After looking through the code, there are two datawave iterators which implement `InterruptibleIterator`, [SortedMultiMapIterator](https://github.com/NationalSecurityAgency/datawave/blob/integration/warehouse/ingest-core/src/test/java/datawave/iterators/SortedMultiMapIterator.java) and [ColumnRangeIterator](https://github.com/NationalSecurityAgency/datawave/blob/integration/warehouse/query-core/src/main/java/datawave/core/iterators/ColumnRangeIterator.java). 

`SortedMultiMapIterator` is used for a test case so it could probably be modified to implement a public iterator class without too much impact to other code behavior. However `ColumnRangeIterator` might need further review to determine the next steps.

2024-09-16 14:59 UTC, ivakegg commented
Ok, it appears that whole mechanism is basically OBE.  So essentially, everywhere we were passing InterationInterruptedException should remain as is.  We simply should not be implementing the InterruptibleIterator and hence should not have any flag to check on.  @SethSmucker Please move that whole mechanism, and keep the places where we are passing the InterationInterruptedException back up the stack.

2024-10-09 19:56 UTC, ivakegg commented
If you make the changes in your other PR, then I believe this one becomes OBE and can be closed.  We still need to make sure that exception is thrown up the stack.

2025-05-20 15:28 UTC, alerman approved these changes, later dismissed

2025-05-21 15:50 UTC, ivakegg commented
We need to remove the InterruptibleIterator as you have done.  What I think is that the additional exception is not what we need here.  Instead we should simply make sure that accumulo's IterationInterruptedException can pass through.  So that means we probably should not be catching that exception anywhere.  I will put this in the PR.

2025-05-21 16:04 UTC, closed without merging