Add feature to exclude datatypes
NationalSecurityAgency/datawave pull request #2548
Opened 2024-09-05 19:58 UTC by jack-gitdev

2024-09-05 20:38 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
> +                if (typeFilter.isEmpty()) {
throw an error if your ignoring due to the typeFilter being non-empty

2024-09-05 20:38 UTC, FineAndDandy approved these changes

2024-09-05 20:39 UTC, FineAndDandy requested changes
can you add a unit test that covers the new functionality?

2024-09-06 13:24 UTC, ivakegg requested changes

2024-09-06 13:24 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
> +                        for (Type<?> type : metadataHelper.getAllDatatypes()) {
These are the wrong data types.  I know this is highly confusing, but these data types are the types assigned to fields (e.g. LcNoDiacritics).  Unfortunately we chose the initial "datatype" designation unwisely.  So "datatype" really needs a qualifier of some sort.  Field datatype vs event or ingest datatype ?  IngestDataTypes is used for various method parameters in the MetadataHelper.   Anyway, the method metadataHelper.getDatatypes((Set<String>)null) will get the data types you are looking for.

2024-09-10 20:18 UTC, FineAndDandy requested changes

2024-09-10 20:18 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/tables/ShardQueryLogic.java
> +                typeFilter.removeAll(excludeSet);
consider adding a test that there is at least one dataType left?

2024-09-10 21:23 UTC, jack-gitdev commented
Need to rework unit tests and add data to testing environment. Current data set does not support testing of necessary edge cases.

2024-09-11 20:44 UTC, jack-gitdev commented
Added data to the test data set, adjusted ShardQueryLogicTest to support the expectation of no results, and adjusted unit tests affected by the addition of new data. Removed draft status.

2024-09-26 16:12 UTC, FineAndDandy approved these changes

2024-10-02 15:18 UTC, ivakegg approved these changes

2024-10-03 17:41 UTC, merged