Updating hadoop to 3.4.0
NationalSecurityAgency/datawave pull request #2559
Opened 2024-09-12 22:39 UTC by alerman

2024-09-13 12:29 UTC, apmoriarty submitted a review, later dismissed

2024-09-20 19:41 UTC, avgAGB submitted a review, later dismissed

2024-11-20 19:24 UTC, keith-ratcliffe requested changes

2024-11-20 19:24 UTC, keith-ratcliffe commented on pom.xml
>          <version.hadoop-shaded>1.1.1</version.hadoop-shaded>
We should update `version.hadoop-shaded` to 1.2.0, since that's what [3.4.0](https://github.com/apache/hadoop/blob/rel/release-3.4.0/hadoop-project/pom.xml#L99) depends on

2024-12-03 13:35 UTC, alerman commented on pom.xml
>          <version.hadoop-shaded>1.1.1</version.hadoop-shaded>
Done. Please review.

2024-12-03 16:12 UTC, keith-ratcliffe submitted a review, later dismissed

2024-12-17 20:21 UTC, avgAGB submitted a review, later dismissed

2024-12-28 01:32 UTC, avgAGB approved these changes, later dismissed

2025-02-04 16:36 UTC, keith-ratcliffe requested changes

2025-02-04 16:36 UTC, keith-ratcliffe commented on pom.xml
> +        <version.hadoop-shaded>1.2.0</version.hadoop-shaded>
Re-reviewing this in light of recent events.
3.4.1 needs `version.hadoop-shaded` == `1.3.0`

2025-02-04 16:36 UTC, keith-ratcliffe commented on pom.xml
> +                <artifactId>hadoop-shaded-protobuf_3_21</artifactId>
3.4.1 needs `hadoop-shaded-protobuf_3_25`

2025-02-04 16:36 UTC, keith-ratcliffe commented on web-services/deploy/application/pom.xml
> +                                            <artifactId>hadoop-shaded-protobuf_3_21</artifactId>
Same as above

2025-02-04 16:36 UTC, keith-ratcliffe commented on web-services/deploy/application/src/main/wildfly/overlay/modules/org/apache/hadoop/common/main/module.xml
> +        <resource-root path="hadoop-shaded-protobuf_3_21-${version.hadoop-shaded}.jar"/>
Same as above

2025-02-04 16:36 UTC, keith-ratcliffe commented on web-services/map-reduce/pom.xml
> +            <artifactId>hadoop-shaded-protobuf_3_21</artifactId>
Same as above

2025-03-10 15:38 UTC, alerman commented on pom.xml
> +        <version.hadoop-shaded>1.2.0</version.hadoop-shaded>
next commit.

2025-03-10 15:40 UTC, alerman commented on pom.xml
> +                <artifactId>hadoop-shaded-protobuf_3_21</artifactId>
next commit

2025-03-10 15:41 UTC, alerman commented on web-services/deploy/application/pom.xml
> +                                            <artifactId>hadoop-shaded-protobuf_3_21</artifactId>
next commit

2025-03-10 15:59 UTC, keith-ratcliffe approved these changes

2025-07-01 15:21 UTC, apmoriarty approved these changes

2025-07-18 11:18 UTC, merged