Remove nonpublic Accumulo InterruptibleIterator
NationalSecurityAgency/datawave pull request #2562
Opened 2024-09-16 21:02 UTC by SethSmucker

IterationInterruptedException and InterruptibleIterator are not part of Accumulo's public API.

Remove InterruptibleIterator, replacing it with SortedKeyValueIterator. InterruptibleIterator was the only reference to IterationInterruptedException.

part of https://github.com/NationalSecurityAgency/datawave/issues/2443

2024-10-03 21:05 UTC, avgAGB approved these changes, later dismissed

2024-10-09 19:44 UTC, ivakegg approved these changes

2024-10-09 19:54 UTC, ivakegg commented on warehouse/ingest-core/src/test/java/datawave/iterators/SortedMultiMapIterator.java
> -        this.interruptFlag = flag;
I believe we can now remove this flag as well and places where we use it in this class.

2024-11-01 16:31 UTC, ivakegg requested changes
Remote unused flag

2025-05-21 15:35 UTC, ivakegg commented on warehouse/ingest-core/src/test/java/datawave/iterators/SortedMultiMapIterator.java
>      private int interruptCheckCount = 0;
Remove the interruptCheckCount?

2025-05-21 19:12 UTC, ivakegg approved these changes

2025-05-21 23:09 UTC, avgAGB approved these changes

2025-05-23 17:19 UTC, merged