fixed python2 and 3 compatibility issues w docker-quickstart scripts
NationalSecurityAgency/datawave pull request #2618
Opened 2024-10-23 11:30 UTC by skyler-kv

Fixed the scripts within docker-quickstart that used Python, `query.sh` and `tvmaze-api-query.sh` were affected and now support Python2 and Python3. `ingest-tv-shows.sh` now works correctly. Added Python3 to `Dockerfile`

Fixes issue #2611

2024-10-23 12:58 UTC, foster33 commented on contrib/datawave-quickstart/bin/query.sh
> +            local exitStatus=$?
There are some places throughout your changes where lines are indented incorrectly. Here in this example, you can see the extra indentation in front of the `PY3` and `PY2` variables all the way down to the closing of the if statement. We should probably change that, and make sure each line is properly indented.

2024-10-23 12:58 UTC, foster33 commented on contrib/datawave-quickstart/bin/query.sh
> +        PY2=$(which python2 2>/dev/null)
I would be interested to see if you could find a way to simplify this a little more. This approach adds some repeating code to handle the two cases. Maybe you could try to consolidate them into one variable, so you do not have to repeat any code.

2024-10-23 12:58 UTC, foster33 commented on contrib/datawave-quickstart/bin/services/datawave/ingest-examples/tvmaze-api-query.sh
> +  fi
Here is another example of the incorrect indentation.

2024-10-23 16:53 UTC, foster33 approved these changes
LGTM. Tested the changes.

2024-10-23 20:43 UTC, keith-ratcliffe approved these changes, later dismissed
lgtm

2024-10-24 15:46 UTC, foster33 commented on contrib/datawave-quickstart/bin/query.sh
> +    PY_CMD='"from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True)"'
This seems to differ from the `PY_CMD` variable in `tvmaze-api-query.sh`. We probably want to remove the double quotes and include the missing parenthesis.
```suggestion
    PY_CMD='from __future__ import print_function; import sys,json; data=json.loads(sys.stdin.read()); print(json.dumps(data, indent=2, sort_keys=True))'
```

2024-10-24 15:50 UTC, foster33 requested changes
See latest comment

2024-10-24 16:00 UTC, foster33 approved these changes

2024-10-30 12:37 UTC, apmoriarty approved these changes

2024-10-30 13:26 UTC, merged