Add cache to record IndexExpansion failures
NationalSecurityAgency/datawave pull request #2659
Opened 2024-12-04 13:19 UTC by apmoriarty

Add caches to record failures to expand range and regex terms against the global index.

2024-12-09 23:05 UTC, FineAndDandy requested changes
Overall looks good. I'd like to see you revisit all the naming of the new objects to clearly convey the limits of the cache.

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/cache/LookupCache.java
> +        // only recording failures, so cache miss returns a true value
took me a minute to understand this

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/cache/LookupCache.java
> +        // only recording failures, so cache miss returns a true value
maybe Failure needs to be in the name? To indicate it is a failure cache, so missing is not a failure?

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +            super(node, new ExceededIndexLookup(), false, false);
set ExceededIndexLookUp to a static final?

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeIndexExpansionVisitor.java
> +                        return buildIndexLookup(node, true, false, ExceededIndexLookup::new);
reference immutable static final

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeIndexExpansionVisitor.java
> +                    LookupCache lookupCache) throws TableNotFoundException {
I'd like to see this renamed to capture that its only really caching failures

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +    protected LookupCache lookupCache = null;
please rename this failedLookupCache

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
> +            return buildIndexLookup(node, false, false, ExceededIndexLookup::new);
can reference an immutable static final

2024-12-09 23:05 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
> +
this can move up into BaseIndexExpansionVisitor with a stub for getKey() to be implemented in each impl

2024-12-10 15:05 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/lookups/cache/LookupCache.java
> +        // only recording failures, so cache miss returns a true value
Renamed to LookupFailureCache in next commit

2024-12-10 15:06 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BaseIndexExpansionVisitor.java
> +            super(node, new ExceededIndexLookup(), false, false);
Extracted ExceededIndexLookup to a private static final object

2024-12-10 15:09 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/BoundedRangeIndexExpansionVisitor.java
> +                        return buildIndexLookup(node, true, false, ExceededIndexLookup::new);
the supplier in the method args doesn't like that, I might circle back to this

2024-12-10 15:30 UTC, apmoriarty commented on warehouse/query-core/src/main/java/datawave/query/jexl/visitors/RegexIndexExpansionVisitor.java
> +            return buildIndexLookup(node, false, false, ExceededIndexLookup::new);
it cannot

2024-12-12 00:23 UTC, FineAndDandy approved these changes

2024-12-31 18:54 UTC, closed without merging

2024-12-31 18:54 UTC, apmoriarty commented
Declined after testing proved this wasn't impactful enough.