fixes #927 Always move the next highest key in AndIterator
NationalSecurityAgency/datawave pull request #932
Opened 2020-10-07 12:46 UTC by FineAndDandy

2020-10-07 15:46 UTC, apmoriarty submitted a review, later dismissed

2020-10-08 20:24 UTC, ivakegg requested changes

2020-10-08 20:24 UTC, ivakegg commented on warehouse/query-core/src/main/java/datawave/query/iterator/logic/AndIterator.java
> +            includeHeads = moveIterators(highest, to);
Are we risking a stack overflow here?

2020-10-13 19:43 UTC, FineAndDandy commented on warehouse/query-core/src/main/java/datawave/query/iterator/logic/AndIterator.java
> +            includeHeads = moveIterators(highest, to);
this call is not on the set, but on a single value. This is not recursive.

2020-10-19 13:46 UTC, ivakegg approved these changes

2020-10-19 14:21 UTC, FineAndDandy commented
closing this in favor of a later more stable release

2021-02-23 21:01 UTC, closed without merging